### ISSUE TITLE
New York Service Territory Boundary

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#4]
### Feature Request
Can we create a layer that is automatically populated that simply shows utility service territories in New York that isn't as data heavy as the US Energy Mapper layer. 

Another option would be creating a layer based upon the New York load zone maps, which show the different load zones and tie to utilities.

**Comment by eanderson4** [comment]
Here is a tile layer configuration.  I would have to add the ability to query a custom endpoint to make it work.  Here is source https://data.ny.gov/Energy-Environment/NYS-Electric-Utility-Service-Territories/q5m9-rahr
```
map:
  layers:
    nyterritory:
      name: New york Service Territory
      show: false
      tags:
        - electric territory
        - name: new york
          type: region
      type: tilelayer
      url: >-
        https://data.ny.gov/tiles/awza-4vgu/the_geom/{zoom}/{x}/{y}.png?$limit=200000&$overscan=32&$mondara=true&$style=%23main%2C%20%23multipoint%2C%20%23point%20%7Bline-width%3A%202.0%3Bline-color%3A%20%23000%3Bline-opacity%3A0.85%3Bmarker-width%3A%208.0%3Bmarker-fill%3A%20%23fb5e2e%3Bmarker-line-color%3A%20%23000%3Bmarker-line-width%3A%202.0%3Bmarker-allow-overlap%3A%20true%3B%7D%23multipolygon%2C%20%23polygon%20%7Bpolygon-fill%3A%20%23AAAAAA%3Bpolygon-opacity%3A%200.5%3Bline-width%3A%201%3Bline-opacity%3A%200.5%3Bline-color%3A%20%23000000%3Bline-simplify%3A%202%7D%23multilinestring%2C%20%23linestring%20%7Bline-width%3A%202.0%3Bline-color%3A%20%230000ff%3Bline-opacity%3A%200.75%3Bline-simplify%3A%202%7D
```

**Comment by eanderson4** [comment]
In latest release I added query support for the tile layer via the following config

```
nyterritory:
      name: New York Service Territories
      query: >-
        https://data.ny.gov/api/geospatial/awza-4vgu?lat={lat}&lng={lng}&zoom={zoom}
      show: false
      tags:
        - electric territory
        - name: new york
          type: region
      type: tilelayer
      url: >-
        https://data.ny.gov/tiles/awza-4vgu/the_geom/{zoom}/{x}/{y}.png?$limit=200000&$overscan=32&$mondara=true&$style=%23main%2C%20%23multipoint%2C%20%23point%20%7Bline-width%3A%202.0%3Bline-color%3A%20%23000%3Bline-opacity%3A0.85%3Bmarker-width%3A%208.0%3Bmarker-fill%3A%20%23fb5e2e%3Bmarker-line-color%3A%20%23000%3Bmarker-line-width%3A%202.0%3Bmarker-allow-overlap%3A%20true%3B%7D%23multipolygon%2C%20%23polygon%20%7Bpolygon-fill%3A%20%23AAAAAA%3Bpolygon-opacity%3A%200.5%3Bline-width%3A%201%3Bline-opacity%3A%200.5%3Bline-color%3A%20%23000000%3Bline-simplify%3A%202%7D%23multilinestring%2C%20%23linestring%20%7Bline-width%3A%202.0%3Bline-color%3A%20%230000ff%3Bline-opacity%3A%200.75%3Bline-simplify%3A%202%7D
```
