### ISSUE TITLE
Map - Improve asset info box

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#45]
### Subject of the issue
Improve the info boxes of assets.

### Feature Request
Currently, drawing items have better info boxes then assets.  Allow settings in asset type config to define which key value pairs should be display.

example config
```yaml
mapsummary:
   fields:
      - get: 'path to variable'
      - name: 'Variable name' 
```

In the map info box, when an asset is selected it should
1. grab type config
2. display key value pairs according to the fields list

This may be able to be improved by using parameter configs, and just listing the parameter group and key.  But this is easier for now and really just want to at least add some basics for parcels and maybe substation and transmission.
